### PR TITLE
Get email for logged in user if your app is whitelisted

### PR DESCRIPTION
**Pull request by peterwarbo**
If your app is whitelisted at Twitter you can get user's email address by setting the property email: true.

passport.use(new TwitterStrategy({
            consumerKey: config.twitter.clientID,
            consumerSecret: config.twitter.clientSecret,
            callbackURL: config.twitter.callbackURL,
            email: true
        }

### CODE REVIEW

**Comment by peterwarbo** [comment]
So what do you think about this feature?

**Comment by nevi-me** [comment]
I've tested this now, and I can't get an email address back. Code looks fine, so I don't know what the cause is

**Comment by juanjoLenero** [comment]
This is great, but wouldn't it be better to allow the user to pass in custom parameters? It would be more future proof, here are the current parameters accepted by the `verify_credentials` endpoint as per twitter's current docs:
image

**Comment by teamnorge** [comment]
I would also vote for the general solution with the possibility to submit other parameters, as I did it locally. Would also notice that the profile received with show.json and verify_credentials.json are not 100% the same, but the difference is really minimal. For example if your locale is different from en_US you may receive the name of the country from show.json with the en_US locale and from verify_credentials.json with the locale you specified at your twitter account.

**Comment by rodrigogs** [comment]
You just rolled it back at b82de46

**Comment by jaredhanson** [comment]
How do you figure that?

**Comment by rodrigogs** [comment]
"email: true" option will no longer work, later I found out that you replaced by includeEmail.

Is it documented somewhere?

Also, I couldn't make it work... And my app seems to be whitelisted :/

**Pull request merged**
